### ISSUE TITLE
Implement internationalization

### ISSUE THREAD

**Issue by ah593** [ah593/mywebclass-simulation-intermediate#17]

**Comment by DemiScript** [comment]
**Completed/Done**

- [x] Developed a webpage in French:
https://github.com/ah593/mywebclass-simulation-intermediate/blob/master/pages/internationalization/index_boostrapfrench.html

- [x] Developed a webpage in Spanish
https://github.com/ah593/mywebclass-simulation-intermediate/blob/master/pages/internationalization/index_boostrapspanish.html
