### ISSUE TITLE
Implement GDPR compliance

### ISSUE THREAD

**Issue by ah593** [ah593/mywebclass-simulation-intermediate#19]

**Comment by DemiScript** [comment]
Checklist to complete this issue

- [ ] Designate a Data Protection Officer (DPO) if required by law.
- [ ] Review and update your privacy policy to ensure that it meets GDPR requirements.
- [x] Obtain explicit consent from users for data collection and processing.
- [x] Provide users with a clear and concise explanation of the data you collect, how you process it, and who you share it with.
- [x] Implement data protection measures such as encryption, access controls, and secure data storage.
- [ ] Provide users with the ability to access, modify, and delete their personal data.
- [ ] Notify users in the event of a data breach within 72 hours.
- [ ] Conduct a Data Protection Impact Assessment (DPIA) to identify and mitigate privacy risks.
- [ ] Obtain consent from users for automated decision-making processes.
- [ ] Implement GDPR-compliant data processing agreements with third-party service providers.
