### ISSUE TITLE
Implement Google Analytics Consent Mode API

### ISSUE THREAD

**Issue by ah593** [ah593/mywebclass-simulation-intermediate#21]

**Comment by DemiScript** [comment]
**Need to publish our fully completed page**
For now we have the provided mywebclass.org page

- [x] Create a Google Analytics property: If you haven't already, create a Google Analytics property and obtain your tracking ID.
- [ ] Set up your website's cookie consent mechanism: You will need to implement a cookie consent mechanism on your website to obtain user consent for Google Analytics tracking.
- [ ] Add the Google Analytics script to your website: Add the Google Analytics tracking script to your website as you normally would
