### ISSUE TITLE
Create privacy policy document

### ISSUE THREAD

**Issue by ah593** [ah593/mywebclass-simulation-intermediate#6]
1. As a user, I want the privacy policy page to be clearly linked and accessible from the home page so that I can easily find and read the policy.
2. As a user, I want the privacy policy page to be clearly written and easily understandable so that I can make an informed decision about my data privacy.
3. As a user, I want the privacy policy page to be GDPR-compliant and clearly state how my data will be collected, stored, and used by the website.

**Comment by DemiScript** [comment]
https://github.com/ah593/mywebclass-simulation-intermediate/blob/master/pages/privacy_boostrap.html
